
service: serverless-node
custom:
  secrets: ${file(secrets.json)}
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: us-east-1
  environment:
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USERNAME: ${self:custom.secrets.DB_USERNAME}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}
      - ${self:custom.secrets.SUBNET4_ID}

functions:
  getCard:
    handler: handler.getCard
    events:
      - http:
          path: /
          method: get
          cors: true

  addCard:
    handler: handler.addCard
    events:
      - http:
          path: /create-card
          method: post
          cors: true

  updateCard:
    handler: handler.updateCard
    events:
      - http:
          path: /update-card/{id}
          method: put
          cors: true

  destroyCard:
    handler: handler.destroyCard
    events:
      - http:
          path: /delete-card/{id}
          method: delete
          cors: true
plugins:
  - serverless-offline
